on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

env:
  ENVIRONMENT: balena-cloud.com

jobs:
  balena-cloud-build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleets: [balena/testbot-rig, balena/testbot-rig-beta, balena/testbot-personal]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: balena-io/deploy-to-balena-action@v0.10.7
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: ${{ matrix.fleets }}
          versionbot: true
          environment: ${{ env.ENVIRONMENT }}
